name: compile pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/extra

    steps:
      # checkout repo contents
      - uses: actions/checkout@v4

      # Make script executable
      - name: Make script executable
        run: chmod +x ./pandoc-commands.sh

      # Run pandoc using sh
      - name: run pandoc
        run: sh ./pandoc-commands.sh

      # output generated file to build artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: "output.*"