name: compile pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/extra

    steps:
      # checkout repo contents
      - uses: actions/checkout@v4

      # Debug: List directory contents and check file existence
      - name: Check files and directories
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Script status:"
          if [ -f "./pandoc-commands.sh" ]; then
            echo "Script exists"
          else
            echo "Script does not exist"
          fi

      # Make script executable with explicit path
      - name: Make script executable
        run: |
          chmod +x ./pandoc-commands.sh
          ls -la ./pandoc-commands.sh

      # Run pandoc using bash explicitly
      - name: run pandoc
        shell: bash
        run: bash ./pandoc-commands.sh

      # output generated file to build artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: "output.pdf"