name: compile pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container: 
      image: pandoc/extra

    steps:
      # checkout repo contents
      - uses: actions/checkout@v4

      # run pandoc to generate pdf from markdown
      - name: run pandoc
        run: |
          pandoc --verbose "./src/input.md" -o "output.pdf" --template /.pandoc/templates/eisvogel.latex

      # output generated file to build artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: "output.pdf"
