name: compile on release

on: release

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/extra

    steps:
      # checkout repo contents
      - uses: actions/checkout@v4

      # Make script executable
      - name: Make script executable
        run: chmod +x ./pandoc-commands.sh

      # run pandoc using external script
      - name: run pandoc
        run: ./pandoc-commands.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output.pdf